---
id: kronolith
name: Kronolith
full: Calendar and scheduling application
description: >-
  Kronolith is the Horde calendar application. It provides web-based calendars
  backed by a SQL database or a Kolab server. Supported features include Ajax
  and mobile interfaces, shared calendars, remote calendars, invitation
  management (iCalendar/iTip), free/busy management, resource management,
  alarms, recurring events, and a sophisticated day/week view which handles
  arbitrary numbers of overlapping events.
list: ~
type: application
homepage: https://www.horde.org/apps/kronolith
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 5.0.0alpha6
  api: 5.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: GPL-2.0-only
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/content: ^3
      horde/horde: ^6
      horde/auth: ^3
      horde/autoloader: ^3
      horde/core: ^3
      horde/data: ^3
      horde/date: ^3
      horde/date_parser: ^3
      horde/dav: ^2
      horde/eventdispatcher: ^1
      horde/exception: ^3
      horde/form: ^3
      horde/group: ^3
      horde/http: ^3
      horde/history: ^3
      horde/icalendar: ^3
      horde/itip: ^3
      horde/image: ^3
      horde/lock: ^3
      horde/logintasks: ^3
      horde/mail: ^3
      horde/mime: ^3
      horde/nls: ^3
      horde/notification: ^3
      horde/perms: ^3
      horde/serialize: ^3
      horde/share: ^3
      horde/support: ^3
      horde/text_filter: ^3
      horde/timezone: ^2
      horde/url: ^3
      horde/util: ^3
      horde/view: ^3
    ext:
      gettext: '*'
      json: '*'
      SimpleXML: '*'
  optional:
    composer:
      horde/nag: ^5
      horde/timeobjects: ^3
      horde/activesync: ^3
      horde/backup: ^2
      horde/db: ^3
      horde/openxchange: ^2
      pear/date_holidays: '*'
    ext:
      xmlwriter: '*'
  dev:
    composer:
      horde/nag: ^5
      horde/timeobjects: ^3
      horde/activesync: ^3
      horde/backup: ^2
      horde/db: ^3
      horde/openxchange: ^2
      horde/test: ^3
      pear/date_holidays: '*'
